sonar.projectKey=digitalization_digi-document-management
sonar.projectName=digi-document-management
sonar.organization=mcodevisionaryorg
sonar.sources=src/DigiDocumentManagement
sonar.tests=tests
sonar.cs.opencover.reportsPaths=**/coverage.opencover.xml
sonar.sourceEncoding=UTF-8
